# Generated by Django 3.2.19 on 2023-07-03 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_item_item_user_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_user_owned',
        ),
        migrations.AddField(
            model_name='item',
            name='item_user_owned',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
