# Generated by Django 3.2.19 on 2023-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230703_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_instructions_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
