# Generated by Django 3.2.19 on 2023-06-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_county_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='zipcode',
        ),
    ]
