# Generated by Django 3.2.19 on 2023-06-29 12:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_postcode_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='Texas', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
