# Generated by Django 3.2.19 on 2023-07-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('checkout', '0006_auto_20230630_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='siteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user.siteuser'),
        ),
    ]
