# Generated by Django 3.2.19 on 2023-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_name', models.CharField(max_length=50)),
                ('newsletter_email', models.EmailField(max_length=100)),
                ('newsletter_city', models.BooleanField(default=True)),
                ('newsletter_space', models.BooleanField(default=True)),
                ('newsletter_castle', models.BooleanField(default=True)),
                ('newsletter_train', models.BooleanField(default=True)),
            ],
        ),
    ]
