# Generated by Django 3.2.19 on 2025-04-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newsletteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='newsletter_castle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='newsletter_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='newsletter_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='newsletter_train',
            field=models.BooleanField(default=False),
        ),
    ]
